auth:
  password: redis
master:
  service:
    type: NodePort
  persistence:
    size: 256Mi
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 512Mi
      cpu: 500m
replica:
  replicaCount: 1
  service:
    type: NodePort
  persistence:
    size: 256Mi
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 512Mi
      cpu: 500m