auth:
  password: redis
master:
  service:
    type: NodePort
  persistence:
    size: 1Gi
  resources:
    requests:
      memory: 1Gi
      cpu: 1
replica:
  replicaCount: 1
  service:
    type: NodePort
  persistence:
    size: 1Gi
  resources:
    requests:
      memory: 1Gi
      cpu: 1