auth:
  password: redis
master:
  service:
    type: NodePort
  persistence:
    size: 256Mi
  resources:
    limits:
      memory: 128Mi
      cpu: 200m
    requests:
      memory: 128Mi
      cpu: 200m
replica:
  replicaCount: 1
  service:
    type: NodePort
  persistence:
    size: 256Mi
  resources:
    limits:
      memory: 128Mi
      cpu: 200m
    requests:
      memory: 128Mi
      cpu: 200m